RA-13-Recipe-Screen
DenisGubernatorov/RecipesApp pull request #11
Opened 2024-12-19 06:45 UTC by DenisGubernatorov

1. Реализация экрана рецепта. Доработа лэйата
2. Добавлены лэйауты для элементов ресайклеров
3. Реализация ресайклеров в коде

2024-12-19 07:08 UTC, DenisGubernatorov commented
1.  На изображении в шапке рецепта должен быь значок "Избранное" но что-то я в макете не нашел пустого значка такого размера. Есть только маленькие, на кнопку. Использовал его
2. В задаче написано, что nestedscrollview должен  быть  основном контейнером. Но тогда как-то не красиов получается. Шапка тоже скролится. Шапку сделал ститческой. А вот все остальное в nestedscrollview добавил. Или я не очень понял что такое основой контейнер... 
3. Может я как-то не так понимаю. Но у меня ожидаемое взаимное поведение у скроллера и ресайклеров было что экран может скроллится отдельно, а контент ресайклеров отдельно. Ну типа если список ингридентов растягивает свою вьюху на всю видимую область, и, при этом, всеравно полностью не выводится. То оснвной экран долже иметь возможность прокрутиться до "Способ" и сам список ингридиентов тоже должен прокручиваться. Но самое лучшее чего смог добиться это как сечас. Т.е. в "Ингредиенты" и "Способ" выводятся полные списки. А основной экран просто прокручивается. 
4. На моем телефоне отображается с багом.
![image](https://github.com/user-attachments/assets/9cf83701-0191-4415-9d49-d9d963f06e23)
Если название ингридента не помещается в свою вьху по длине и переносится на другую строку, то тогда под вьхой для количества и единиц имзерения появляется основной фон.
P.S.  Походу на полноценный ПР это не тянет :)) Ну хоть начать ошибки обсуждать

2024-12-19 11:33 UTC, Churickoid requested changes
1. Векторные изображения и отличаются от обычных пнгшек, что они могут принимать любые размеры. Нужно импортировать иконку сердца с нужным размером
2. По заданию подразумевается, что шапка тоже скролится. Можешь оставить как тебе нравится
3. В constrainLayout чтоб всё работало корректно, нужно указывать адекватно по каким объектам ограничена твоя вью. У твоей NestedScrollView нету ограничания по низу,  из-за этого он отрисовывает какие-то свои размеры объекта. Достаточно прописать у NestedScrollView app:layout_constraintBottom_toBottomOf="parent"
4) Сделай в вёрстке чтоб текст с количеством занимал match_parent

Всё что внутри nestedScrollView надо переделывать. Каждый Layout жрёт довольно много памяти, в твоём случае можно обойтись только рутовым constrainLayout и одним linearLayout внутри скроллВью. Сейчас всё это очень не оптимизировано работает. 
Также глянь как всё это выглядит в фигме, сейчас не хватает отступов у по вертикали и горизонтали. Между текстом и ресайклер вью отступы не те

2024-12-19 11:44 UTC, Churickoid requested changes

2024-12-19 11:44 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/RecipeFragment.kt
> +            )
Сейчас divider не соответсвует дизайну, настрой эти параметры для него
isLastItemDecorated
dividerInsetStart 
dividerInsetEnd 
dividerColor
dividerThickness

2024-12-19 11:44 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/RecipeFragment.kt
> +            MaterialDividerItemDecoration(
Зачем создавать два одинаковых объекта для дивайдеров, если можно использовать один в двух местах

2024-12-19 11:44 UTC, Churickoid commented on app/src/main/res/values/strings.xml
> +    <string name="method_title">Способ</string>
В макете другая надпись

2024-12-19 11:44 UTC, Churickoid commented on app/src/main/res/layout/recipe_fragment.xml
> +        android:padding="@dimen/cat_header_padding"
Какой-то оромный список параметров здесь, многое можно вынести в стиль. Также лучше поменять название стиля, он не только в categoy используется. Всё писать в одном стиле snake_case или camelCase

2024-12-21 19:29 UTC, Churickoid requested changes
Экран должен выглядит 1 в 1 как на макете их фигмы. Как минимум в item нужно добавить нужные padding, у заднего фона recyclerView должны быть скосы по углам, как ты это раньше делал для текста в шапке

2024-12-21 19:29 UTC, Churickoid commented on app/src/main/res/layout/recipe_fragment.xml
> +        android:layout_marginBottom="@dimen/recipe_screen_bottom_13dp"
Не понимаю смысла этого Марджина,  пустота между кнопками и фрагментами только выросла

2024-12-23 20:00 UTC, Churickoid approved these changes
Молодец, всё верно!

2024-12-23 20:00 UTC, aGroupoid commented on app/src/main/res/layout/recipe_fragment.xml
> +                android:id="@+id/ingredients_block_header"
Не вижу смысла в этом linearLayout, у тебя уже есть textView "Список рецептов" , которая нормально отображается без linearLayout. Каждый лишний лейаут -  дополнительная нагрузка на систему

2024-12-24 18:44 UTC, merged