RA-14-SeekBar
DenisGubernatorov/RecipesApp pull request #12
Opened 2024-12-25 21:28 UTC by DenisGubernatorov

1) Реализация seekBar для количества порций

2024-12-26 14:01 UTC, Churickoid requested changes

2024-12-26 14:01 UTC, aGroupoid commented on app/src/main/res/layout/recipe_fragment.xml
> +                android:progress="0">
Давай установим min, progress = 1 параметры, как ты сделал для max. Тогда не придется прибавлять эту непонятную магическую единичку в листенере

2024-12-26 14:01 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/IngredientsAdapter.kt
> +                DecimalFormat("#,###.#").format(value)
Вообще для чисел с точкой лучше использовать BigDecimal. Он позволяет точнее сравнивать и производить вычисления. Плюс есть встроенные методы для форматирования строк. Статья про BigDecimal: https://javarush.com/groups/posts/2274-kak-ispoljhzovatjh-bigdecimal-v-java

val totalQuantity = BigDecimal(ingredientCurrentCount) * BigDecimal(quantity)

val displayQuantity = totalQuantity
.setScale(1,RoundingMode.HALF_UP)
.stripTrailingZeros()
.toPlainString()

2024-12-26 14:01 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/RecipeFragment.kt
> +            override fun onProgressChanged(p0: SeekBar?, p1: Int, p2: Boolean) {
Те параметры, которые используешь - нужно назвать внятными именами, p1 - непонятно что значит

2024-12-26 16:23 UTC, DenisGubernatorov commented on app/src/main/res/layout/recipe_fragment.xml
> +                android:progress="0">
Получается что теперь допустимое состояние 0 порций. 
![image](https://github.com/user-attachments/assets/dcca4adc-f741-4132-8785-9a0842208a12)
Как-то не очень логично на мой взгляд. Как минимум пишется количество ингридиентов на 1 порцию

2024-12-27 09:22 UTC, Churickoid commented
По заданию всё верно, молодец! Поправь в следующем ПР, я в комменте написал, что надо также выставить min = 1 в xml, тогда мы ограничем порции от 1
<img width="237" alt="Снимок экрана 2024-12-27 в 12 21 18" src="https://github.com/user-attachments/assets/a8405a6d-03dd-42bb-b933-03dde3354610" />

2024-12-27 20:14 UTC, merged