RA-04-create-and-show-fragment
DenisGubernatorov/RecipesApp pull request #2
Opened 2024-10-22 21:34 UTC by DenisGubernatorov

1) Поправлены префиксы значений в строковых ресурсах 2) В  gradle добавлена зависимость для использования фрагментов 3) Добавлен класс CategoriesListFragment наследующий Fragment и  файл лэйаут fragment_list_categories.xml 4) В основной лэйату добавлен контейнер для фрагментов 5) В MainActivity создается экземпляр фрагмента и запускается при создании активити

2024-10-23 10:12 UTC, Churickoid requested changes

2024-10-23 10:12 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
> +}
Поскольку жизненный цикл фрагмента длиннее, чем у view внутри него, рекомендуется очищать binding в методе onDestroyView.
Подробнее можно почитать здесь: https://developer.android.com/topic/libraries/view-binding#fragments
Из-за этого внутри фрагментов придется отказаться от lazy. Поскольку очищать его не получится адекватно

2024-10-23 10:12 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +            add(R.id.mainContainer, categoriesListFragment)
Обращаю внимание на установку флага ​​​​setReorderingAllowed(true)​​​​. В [документации](https://developer.android.com/guide/fragments/transactions#reordering) этому посвящен отдельный абзац. Флаг нужен для корректного выполнения транзакции.

2024-10-23 10:12 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
> +class CategoriesListFragment : Fragment(R.layout.fragment_list_categories) {
Здесь передавать в конструктор не надо. Сначала создается макет через конструктор фрагмента, затем в onCreateView через binding.root. Лишний раз перерисовывать фрагмент - плохая практика

2024-10-23 10:12 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +        tools:layout_editor_absoluteX="16dp">
Нужно придерживаться, чтоб макет соответствовал всегда экрану реального приложеня. Этот параметр не нужен, он меняет изображение макета, хоть и не сильно, будет сложнее понять что у пользователей действительно на экране

2024-10-26 12:19 UTC, DenisGubernatorov commented
Извини. Я помню, что ты просил не резолвить здесь комментарии. Я их зарезолвили в самой идешке. Ну и здесь изменения подтянулись. Что-то не подумал об этом. В следующий раз буду просто скрывать комментарии в идешке

2024-10-26 14:38 UTC, Churickoid approved these changes
Всё верно, молодец! Резолвить не критично, но лучше так не делать. Попробуй покапаться в settings ИДЕшки, в разделе гитхаба, может там можно что-то изменить, чтоб локально резолвить но не на сайте

2024-10-28 18:13 UTC, merged