RA-05-create-fragment-for-favorites
DenisGubernatorov/RecipesApp pull request #3
Opened 2024-10-28 21:02 UTC by DenisGubernatorov

1) Добавлен класс для категории Избранное, реализующий Fragment. 2) Добавлены лэйаут fragment_favorites.xml для категории Избранное 3) В MainActivity настроены слушатели кнопок. При нажатии в контейнере FragmentContainerView размещается соответствующий фрагмент

2024-10-29 17:13 UTC, ievetrovdev requested changes

2024-10-29 17:13 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="text_favorites_fragment">Избранное</string>
Повтор ресурса

2024-10-29 17:13 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +            replace(R.id.mainContainer, fragment)
Ты используешь Java метод add/replace из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add() из класса FragmentTransaction.kt. 

Именно для импорта метода add/replace нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

2024-11-02 21:47 UTC, Churickoid approved these changes
Основная логика написано верно, молодец. Добавь фикс при выполнении следующего ПР

2024-11-02 21:47 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +            load<CategoriesListFragment>()
Сейчас стартовый экран тоже получает свойство addToBackStack(null). Такого нам не надо, поскольку при нажатии назад на стартовом экране, пользователь  попадёт в непонятый стейт с пустым экраном без фрагментов. Давай расширим функцию load булевым атрибутом, который по умолчанию true. И добавим условие, добавлять в бэкстек только когда true. В этом месте закидывать в функцию значение false

2024-11-05 18:49 UTC, merged