RA-07-categories-screen
DenisGubernatorov/RecipesApp pull request #5
Opened 2024-11-09 07:39 UTC by DenisGubernatorov

1) Добавление инастройка компонентов для экрана "Категории"

2024-11-09 18:51 UTC, Churickoid requested changes

2024-11-09 18:51 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +        app:layout_constraintTop_toTopOf="parent" />
На макете фрагмента список карточек должен выглядеть также как в фигме. Карточку нужно сверстать до конца и заполнить тестовыми данными через tools.
Также нужно учесть ширину экрана, чтоб карточки занимали всё место по ширине вне зависимости от размеров экрана

2024-11-09 18:51 UTC, Churickoid commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:background="@drawable/bcg_categories"
Давай лучше вынесем в отдельный imageView, у него намного больше настроек, щас фото выглядит мыльно. Текущий scaleType никак не работает в ConstraintLayout

2024-11-09 18:51 UTC, Churickoid commented on app/src/main/res/values/dimens.xml
> +    <dimen name="cat_header_text_size">20sp</dimen>
Дублируется ресурс

2024-11-09 18:51 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <item name="android:padding">8dp</item>
Вынести в ресурсы

2024-11-16 17:32 UTC, Churickoid requested changes

2024-11-16 17:32 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +    android:layout_height="wrap_content">
Текущая вложенность в ConstraintLayout выглядит лишней, его возможности никак не используются,  это лишняя нагрузка на вёрстку. Почему бы не сделать CardView рутовой View?

2024-11-16 17:32 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +                android:layout_weight="2"
Когда ты пропиcываешь конкретную длину, параметр layout_weight становится бесполезным. Лучше его убрать

2024-11-16 17:32 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +                android:layout_height="match_parent"
У твоей CardView стоит длина wrap_content, по контенту внутри. А внутри компонентов его ты пишешь match_parent, мы должны посомтреть какая длина у родителя сначала понять, что он wrap_content и сопаставить эту информацию с тем, что здесь на самом деле получается тоже wrap_content. 
Давай не усложнять себе жизнь и напрямую писать в дочерних элементов wrap_content

2024-11-16 17:32 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +                android:layout_marginBottom="@dimen/margin_half_8_dp"
Есть более униварсальный метод для двух сторон layout_marginVertical. Но в сейчас не хватает marginEnd, длинный текст убдет упираться в границы cardView, на дизайне такого нет. В таком случае все марджины лучше будет просто заменить на margin =

2024-11-16 17:32 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +                android:layout_height="130dp"
Это тоже надо вынести в ресурсы, как и другие элементы до этого

2024-11-16 17:32 UTC, Churickoid commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:scaleType="fitXY"
Текущий scaleType как-то сильно растягивает картинку, давай лучше использовать centerCrop

2024-11-17 11:08 UTC, DenisGubernatorov commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:scaleType="fitXY"
Честно говоря особой разницы не вижу. Можно заметить только в момент когда меняешь значение, что fitXY расятгивает немного. Есть какие-то инструменты? Или просто "насмотренность"?

2024-11-17 18:34 UTC, Churickoid approved these changes
Молодец, всё верно!
По поводу инструментов, ты справа снизу можешь потянуть за угол и менять ширину и высоту макета, на широких экранах прям плохо выгляди fitXYZ, а centerCrop хорошо
![image](https://github.com/user-attachments/assets/f250e986-ce28-449a-8934-9ac7b7fa31b5)

2024-11-23 13:41 UTC, merged