RA-08-RecyclerView-realization
DenisGubernatorov/RecipesApp pull request #6
Opened 2024-11-24 07:29 UTC by DenisGubernatorov

Реализция адаптера для recyclerView + небольшой рефакторинг

2024-11-24 07:31 UTC, DenisGubernatorov commented
Опять сюрприз, когда открыл приложение на реальном телефоне. Картинки в карточках категорий меньше чем на макете и в эмуляторе 
![image](https://github.com/user-attachments/assets/f84c8c89-5b62-4895-b292-65f8e8b07487)
Поигрался с высотой, менял наследование, веса выставить. Что-то такой вариант, как на скрине - самый лучший из того что получалось

2024-11-24 21:21 UTC, Churickoid requested changes
При нажатии на элементы списка - нет никакого эффекта. Добавь cardView эти параметры, чтоб появился ripple
https://gist.github.com/mrsid96/1ec250e793ad914de27722bdda52e0b1

2024-11-24 21:21 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/CategoriesListAdapter.kt
> +
Надо еще добавить “описание контента”. contentDescription используется для предоставления текстового описания для не текстовых элементов, таких как изображения, кнопки с иконками и других графических объектов.
Это происходит так: пользователь водит пальцем по экрану и в зависимости от того, где сейчас активно нажатие – происходит озвучивание. Чтобы перейти в конкретную категорию пользователю нужно совершить двойное нажатие в качестве подтверждения перехода на соответствующую категорию.

Для нединамических фото, достаточно прописать в XML imageView.
Для карточек, менять его в адаптере. Можно задавать картинкам категорий что-то "Изображение категории название_категории".

2024-11-24 21:21 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
> +        binding.rvCategories.layoutManager = GridLayoutManager(requireContext(), 2)
Эти параметры уже прописаны в xml. Дублировать здесь их не надо

2024-11-24 21:21 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="match_parent"
Давай лучше просто захардкодим длину картинки, как на дизайне. На моём устройсте с таким подходом фотка вообще мелкая

2024-11-26 22:24 UTC, DenisGubernatorov commented on app/src/main/java/com/example/recipesapp/CategoriesListAdapter.kt
> +
В сообщении коммита написал, что для того, что бы хорошо было видно riple убрал настройку бэкграунда в лэйауте. Но тогда карточка ужасно смотрится если установлена темная тема. Но это наверное больше вопрос к макету и его реализации в светлой и темной темах
![image](https://github.com/user-attachments/assets/9c1ea608-ed22-430b-b817-b665325b92a2)

2024-11-26 22:31 UTC, DenisGubernatorov commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="match_parent"
Кстати, при повороте телефона для карточек остается "амбразура". Скрин из менеджера запущенных устройств, но на телефоне такие пропорции... Видимо это опять вопрос к макету и к тому, что должен быть вариант компановки для таких случаев :))
![image](https://github.com/user-attachments/assets/1d8fcde0-23d1-4d15-99f2-99b89b949770)

2024-11-27 18:55 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/CategoriesListAdapter.kt
> +
Не совсем понимаю про какой бэкграунд идёт речь. На темной теме, 30 СДК, у меня она хорошо работает. Специфическое поведение твоего девайса и версии видимо
![image](https://github.com/user-attachments/assets/293c7eb8-de7a-449b-b023-32eb3ef3a209)

2024-11-27 18:57 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="match_parent"
Да, это тестовый макет. На реальном приложении был бы макет для другой ориентации, либо пришлось бы пинать дизайнера, чтоб сделал.  Как вариант, могу предложить шапку внести в scrollView, так проблем особо не будет

2024-11-27 18:57 UTC, Churickoid approved these changes
Молодец, всё верно!

2024-12-02 18:27 UTC, merged