Ra 11 burger recipes screen
DenisGubernatorov/RecipesApp pull request #9
Opened 2024-12-08 20:24 UTC by DenisGubernatorov

RA-11-Burger-Recipes-Screen 
1) Подготовка данных
2) RecipesListFragment изменен способ обращение к arguments
3) Верстка шапки RecipesListFragment
4) Реализован RecyclerView для списка рецептов
5) Добавлен Fragment для рецепта. Пока пустой
6) Реализован переход на фрагмент рецепта

2024-12-08 20:39 UTC, Churickoid requested changes

2024-12-08 20:39 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
> +            hide(this@CategoriesListFragment)
В целом, этот параметр лишний. Если тебе нужно скрыть его View, то лучше просто использовать replace вместо add

2024-12-08 20:39 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
>              add(R.id.mainContainer, recipesListFragment)
В прошлых заданиях мы уже использовали более новый котлиновский метод через дженерик (`add<MyFragment>`), давай и дальше продолжать использовать его

2024-12-08 20:39 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/RecipesListFragment.kt
> +        binding.recipesListHeaderImg.contentDescription = "Изображение для категории $categoryName"
Хардкодить текстовые параметры - плохая практика. При смене языка, эта строчка не поменяется. Нужно вынести в строковой ресурсы с параметром.
Здесь описано про это
https://developer.android.com/guide/topics/resources/string-resource?hl=ru#formatting-strings

2024-12-08 20:39 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/RecipeListAdapter.kt
> +            binding.recipeImageView.contentDescription = "Изображение для категории ${recipe.title}"
Та же проблема с хард код строкой

2024-12-08 20:40 UTC, Churickoid requested changes

2024-12-08 20:40 UTC, Churickoid commented on app/src/main/res/values/strings.xml
> +    <string name="recipes_list_img_description">Категория еще в разработке</string>
Тестовые поля, как раз лучше не выносить в ресурсы и просто хард-кодить

2024-12-09 19:00 UTC, DenisGubernatorov commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
> +            hide(this@CategoriesListFragment)
Что-то я "потерялся" :)) Здесь изначально был replace. Но в https://github.com/DenisGubernatorov/RecipesApp/pull/7#discussion_r1867961651 попросил поменять на add. А если здесь использовать add, то было видно предыдущий фрагмент под новым. Поэтому и добавил скрытие.

2024-12-10 06:54 UTC, DenisGubernatorov commented on app/src/main/res/values/strings.xml
> +    <string name="recipes_list_img_description">Категория еще в разработке</string>
Неправильный текст. Это для обязательного атрибута layout/recipes_list_fragment.xml:18

2024-12-10 16:04 UTC, Churickoid approved these changes
По заданию верно, молодец! По поводу наложения, лучше использовать просто add, как я писал раньше. Ты используешь add, но параметров hide, всё откатывается обратно к replace реализации, тогда уж лучше напрямую писать replace.
Скинь в следующем ПР, как это наложение выглядит. Возможно рутовым вьюхам фрагмента достаточно прописать backgroundColor

2024-12-10 21:37 UTC, merged